@startuml


Class User
Class Admin
Class Order
Class Carport
Class Bom
Class Materials

Admin "1"--|{ Order
User "1"--|{ Order
Order "1"--"1" Carport
Order "1"--"1" Bom
Bom }|--|{ Materials






@enduml